// <auto-generated />
using System;
using MISA.WorkShift.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MISA.WorkShift.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyTaxCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_tax_code");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Representative")
                        .HasColumnType("longtext")
                        .HasColumnName("representative");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("CompanyId");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.CompanyUser", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("CompanyId", "UserId");

                    b.ToTable("company_users");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_address");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerLegalName")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_legal_name");

                    b.Property<string>("BuyerName")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_phone");

                    b.Property<string>("BuyerTaxCode")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_tax_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.HasKey("CustomerId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("invoice_id");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_address");

                    b.Property<string>("BuyerBankAccount")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_bank_account");

                    b.Property<string>("BuyerBankName")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_bank_name");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerLegalName")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_legal_name");

                    b.Property<string>("BuyerName")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_phone");

                    b.Property<string>("BuyerTaxCode")
                        .HasColumnType("longtext")
                        .HasColumnName("buyer_tax_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("CqtCode")
                        .HasColumnType("longtext")
                        .HasColumnName("cqt_code");

                    b.Property<int?>("CqtStatus")
                        .HasColumnType("int")
                        .HasColumnName("cqt_status");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("exchange_rate");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("invoice_number");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int")
                        .HasColumnName("invoice_type");

                    b.Property<int>("IssueStatus")
                        .HasColumnType("int")
                        .HasColumnName("issue_status");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext")
                        .HasColumnName("payment_method");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("payment_status");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("pdf_file_path");

                    b.Property<Guid?>("ReferenceInvoiceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_invoice_id");

                    b.Property<string>("SellerAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("seller_address");

                    b.Property<string>("SellerName")
                        .HasColumnType("longtext")
                        .HasColumnName("seller_name");

                    b.Property<DateTime?>("SellerSignedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("seller_signed_date");

                    b.Property<string>("SellerTaxCode")
                        .HasColumnType("longtext")
                        .HasColumnName("seller_tax_code");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("series");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("longtext")
                        .HasColumnName("template_code");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("template_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TotalAmountInWords")
                        .HasColumnType("longtext")
                        .HasColumnName("total_amount_in_words");

                    b.Property<decimal>("TotalBeforeTax")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_before_tax");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_discount");

                    b.Property<decimal>("TotalTaxAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_tax_amount");

                    b.Property<string>("XmlFilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("xml_file_path");

                    b.HasKey("InvoiceId");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.InvoiceDetail", b =>
                {
                    b.Property<Guid>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("detail_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount_rate");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("item_name");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tax_amount");

                    b.Property<int?>("TaxRate")
                        .HasColumnType("int")
                        .HasColumnName("tax_rate");

                    b.Property<string>("UnitName")
                        .HasColumnType("longtext")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.HasKey("DetailId");

                    b.ToTable("invoice_details");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.InvoiceRegistration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<int>("DataTransferMode")
                        .HasColumnType("int")
                        .HasColumnName("data_transfer_mode");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("IdentityNo")
                        .HasColumnType("longtext")
                        .HasColumnName("identity_no");

                    b.Property<int?>("IdentityType")
                        .HasColumnType("int")
                        .HasColumnName("identity_type");

                    b.Property<int>("InvoiceAppType")
                        .HasColumnType("int")
                        .HasColumnName("invoice_app_type");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("longtext")
                        .HasColumnName("issue_place");

                    b.Property<int?>("MethodOfTransfer")
                        .HasColumnType("int")
                        .HasColumnName("method_of_transfer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext")
                        .HasColumnName("nationality");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("longtext")
                        .HasColumnName("registration_no");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("representative_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("SubjectCategory")
                        .HasColumnType("int")
                        .HasColumnName("subject_category");

                    b.Property<string>("TaxAuthorityCode")
                        .HasColumnType("longtext")
                        .HasColumnName("tax_authority_code");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tax_code");

                    b.Property<string>("TaxpayerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("taxpayer_name");

                    b.Property<int>("TransType")
                        .HasColumnType("int")
                        .HasColumnName("trans_type");

                    b.HasKey("RegistrationId");

                    b.ToTable("invoice_registrations");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.InvoiceTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("template_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("CssCustom")
                        .HasColumnType("longtext")
                        .HasColumnName("css_custom");

                    b.Property<string>("InvSeries")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inv_series");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_default");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("template_code");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("template_name");

                    b.Property<string>("XsltContent")
                        .HasColumnType("longtext")
                        .HasColumnName("xslt_content");

                    b.HasKey("TemplateId");

                    b.ToTable("invoice_templates");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.RegDependentUnit", b =>
                {
                    b.Property<Guid>("DependentUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("dependent_unit_id");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_date");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tax_code");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_date");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit_name");

                    b.HasKey("DependentUnitId");

                    b.ToTable("reg_dependent_units");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.RegDigitalSignature", b =>
                {
                    b.Property<Guid>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("signature_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("action_type");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("organization_name");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_date");

                    b.HasKey("SignatureId");

                    b.ToTable("reg_digital_signatures");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.RegInvoiceType", b =>
                {
                    b.Property<Guid>("RegInvoiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("reg_invoice_type_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("InvoiceTypeCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("invoice_type_code");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_selected");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.HasKey("RegInvoiceTypeId");

                    b.ToTable("reg_invoice_types");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.RegSuspension", b =>
                {
                    b.Property<Guid>("SuspensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("suspension_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_date");

                    b.HasKey("SuspensionId");

                    b.ToTable("reg_suspensions");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.RegTVAN", b =>
                {
                    b.Property<Guid>("RegTVANId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("reg_tvanid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.Property<string>("TVANName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tvanname");

                    b.Property<string>("TVANTaxCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tvantax_code");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_date");

                    b.HasKey("RegTVANId");

                    b.ToTable("reg_tvans");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.RegTransmissionUnit", b =>
                {
                    b.Property<Guid>("TransmissionUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("transmission_unit_id");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("registration_id");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tax_code");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_date");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit_name");

                    b.HasKey("TransmissionUnitId");

                    b.ToTable("reg_transmission_units");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("shift_id");

                    b.Property<DateTime?>("BreakEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("break_end");

                    b.Property<DateTime?>("BreakStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("break_start");

                    b.Property<double?>("BreakTime")
                        .HasColumnType("double")
                        .HasColumnName("break_time");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shift_code");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shift_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<double>("WorkingTime")
                        .HasColumnType("double")
                        .HasColumnName("working_time");

                    b.HasKey("ShiftId");

                    b.ToTable("shifts");
                });

            modelBuilder.Entity("MISA.WorkShift.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
